Changed tabular data wrangling notebooks
haesleinhuepf/BioImageAnalysisNotebooks pull request #32
Opened 2023-05-03 17:04 UTC by marabuuu

Hi again @haesleinhuepf,

Here another one for modified __tabular data wrangling__ notebooks:
- Handling NaNs
- Introduction to DataFrames
- Select rows and columns
where I tried to simplify things or make them more visually appealing. I also added a link to a pandas cheat sheet

2023-05-03 18:24 UTC, haesleinhuepf requested changes
Fantastic, thanks @marabuuu ! 

Two little things:
* Can you add your notebooks in the right chapter in `docs/_toc.yml`?
* Let's not ignore csv files in general (see comment below).

Big thanks again!

2023-05-03 18:24 UTC, haesleinhuepf commented on .gitignore
> +*.csv
Ah, we should not ignore all CSV files. Can you change that to the specific csv files you would like to have ignored?

2023-05-05 09:40 UTC, marabuuu commented
Thanks @haesleinhuepf for the hint, it's done now. I have changed the _toc.yml in PR #31 as it is related to feature extraction. 

Best,
Mara

2023-05-08 07:16 UTC, merged

2023-05-08 07:17 UTC, haesleinhuepf commented
Awesome, thanks @marabuuu, also for fixing all my typos 🙊